name: MicroASE CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4 

      - name: Install Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests
        run: newman run test/calc_ut.postman_collection.json
        run: newman run test/string_ut.postman_collection.json
        run: newman run test/integration.postman_collection.json # Specify your collection file

            
