name: MicroASE CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4 

      - name: Install Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.7.1

      # Setup and test calc-service
      - name: Build Docker image for calc service
        run: docker build -t calc-service -f src/calc/Dockerfile src/calc

      - name: Run calc service container
        run: docker run -d --name calc-service -p 5000:5000 calc-service

      - name: Run Postman calc tests
        run: newman run tests/calc_ut.postman_collection.json

      - name: Stop and remove calc service container
        run: docker stop calc-service && docker rm calc-service
